### ISSUE TITLE
Code alignment - Merge issue #8 with issue #9

### ISSUE THREAD

**Issue by antoniokunstek** [foivz/pop-app-backend#25]
- Fix UserController and UserControllerTest class
- Implement SpringSecurity on /activate endpoint

**Comment by mislavmatijevic** [comment]
Prior to this latest fix, any valid JSON syntax would have the same effect as if a request to deactivate a user was sent.
Reasoning is simple: since the boolean property of ActivateUserRequestBody was non-nullable, it would automatically be assigned a value of `false` during parsing.
With it being nullable, on bad body it becomes `null`, throws an exception on non-null assertion and results in a proper "ERR_BAD_BODY" error response.

**Comment by mislavmatijevic** [comment]
@antoniokunstek I'm done _aligning_. I suggest you take a look at changes I've done to your code. Maybe there are some other cases in your activation feature - or in the entire app itself - that are not properly tested yet?
If not, I think we're good here. I leave you to take care of this branch from now, but please make sure to promplty bring a PR in order to clean `develop` of non-compiling tests.

Enjoy the weekend! 🎆

**Comment by antoniokunstek** [comment]
Dear Mislav (@mislavmatijevic),

I checked everything, and I started the tests. The only thing I found wrong was the name of the method (you wrote the test well, only in the name of the method you expected a status of 200, but you got a status of 400), I believe that you were already tired then.

I have to admit that I am fascinated by your programming capabilities, you just left me in wow 🤩. I see that, I still have a lot to learn in designing a software product and writing clean code.

As far as I'm concerned, you can accept PR immediately. What task do you want me to take on next?

Thank you in advance for your reply and I wish you a pleasant weekend.
Best regards!

![image](https://github.com/foivz/pop-app-backend/assets/61520141/62cde518-552e-4df0-8f6a-480558dc2f50)
